### ISSUE TITLE
CORS Policy error 

### ISSUE THREAD

**Issue by rguerra712** [arabold/serverless-react-boilerplate#1]
# This is a Bug Report
## What went wrong?
When you initially clone the repository, then after running `npm install`, then `npm run build:client`, then `npm run deploy` the deploy works just fine, however, on the page that is output, the following error can be found in the console:
```Access to resource at '<s3url>/manifest.json' from origin '<lambda>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```
Which looks related to the configuration for the S3 Bucket.

## What did you expect should have happened?
S3 should be configured for CORS.

## What was the config you used?
The default configuration from a fresh clone.

## Additional data
* Serverless Framework version: 1.36.0
* Operating System: Windows

**Comment by arabold** [comment]
Haven't noticed that but thanks a lot for the update and fix. Merged.
