### ISSUE TITLE
Module not found: Error: Can't resolve '../../dist/stats.json'

### ISSUE THREAD

**Issue by DaxGoon** [arabold/serverless-react-boilerplate#14]
- WARNING in ./src/server/render.tsx
-  @ ./src/server/render.tsx
- @ ./handler.ts

Fails to render both on local host, also on aws.

**Comment by arabold** [comment]
I have updated the repo with the latest dependencies but React. Please check it out. I'm not encountering any issues when following the steps laid out in the `README.md`. What are you trying to do before you run into this error?

**Comment by DaxGoon** [comment]
Thanks for the reply. I have created a nested directory structure and I also use react-router. Those are the only significant changes from the laid out structure. When I destrcture the design into traditional react (without serverless) and run locally, it works perfectly. On 2 Feb 2021 20.28, Andre Rabold <notifications@github.com> wrote:
I have updated the repo with the latest dependencies but React. Please check it out. I'm not encountering any issues when following the steps laid out in the README.md. What are you trying to do before you run into this error?

**Comment by johndanek** [comment]
I fixed this error by adding 

`writeToDisk: true`

in the devServer object of webpack.browser.config.js. For some reason, running yarn start:offline was wiping out the dist/ directory.

**Comment by arabold** [comment]
This has been fixed in the latest update of the app. The `stats.json` is written always now (using `writeToDisk` as @johndanek suggested before), simplifying some of the original setup.
