### ISSUE TITLE
No static content deploying to a region other than us-east-1

### ISSUE THREAD

**Issue by rguerra712** [arabold/serverless-react-boilerplate#3]
# This is a Bug Report
## What went wrong?
When you initially clone the repository, then after running `npm install`, then `npm run build:client`, then run `serverless deploy --region us-east-2` or any region other than `us-east-1`, the output API Gateway url for the lambda does not render any static content,, with an error (in chrome) that the CORS headers are missing.

## What did you expect should have happened?
The same behavior for `us-east-1` should have occurred, largely the static content should have been accessible.

## What was the config you used?
The default configuration from a fresh clone.

## Additional data
* Serverless Framework version: 1.36.0
* Operating System: Windows
* Browser: Chrome

**Comment by arabold** [comment]
I've made one more change as with this PR we couldn't deploy to `us-east-1` anymore (but all others work). Pushed the fix up.

Did you have issues with `serverless-s3-deploy` not deploying _at all_? Right now it doesn't seem to work locally without calling `npx sls s3deploy` manually 🙄

**Comment by rguerra712** [comment]
Thanks for the fix and thanks for merging so quickly. As for `serverless-s3-deploy`, I had no issues from what I could tell, every time everything deployed just fine. Odd.
